# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memoreal.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(341, 349)
        MainWindow.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("brain.png.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(338, 0))
        self.centralwidget.setStyleSheet("background-color: #22222e")
        self.centralwidget.setObjectName("centralwidget")

        self.bar_top = QtWidgets.QFrame(self.centralwidget)
        self.bar_top.setGeometry(QtCore.QRect(0, 0, 341, 71))
        self.bar_top.setStyleSheet("background-color: #fb5")
        self.bar_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bar_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bar_top.setObjectName("bar_top")

        self.lbl_status = QtWidgets.QLabel(self.bar_top)
        self.lbl_status.setGeometry(QtCore.QRect(110, 10, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_status.setFont(font)
        self.lbl_status.setStyleSheet("color:")
        self.lbl_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.btn_back_to_menu = QtWidgets.QPushButton(self.bar_top)
        self.btn_back_to_menu.setGeometry(QtCore.QRect(10, 10, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)

        self.btn_back_to_menu.setFont(font)
        self.btn_back_to_menu.setStyleSheet("QPushButton{\n"
                                            "    background-color: #fb5;\n"
                                            "    border-radius: 25;\n"
                                            "    border: 2px solid  #22222e;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed{\n"
                                            "    color: #fb5;\n"
                                            "    border: 2px solid #fb5;\n"
                                            "    background-color: #22222e;\n"
                                            "}")
        self.btn_back_to_menu.setObjectName("btn_back_to_menu")

        self.bar_menu = QtWidgets.QFrame(self.centralwidget)
        self.bar_menu.setGeometry(QtCore.QRect(0, 70, 335, 278))
        self.bar_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bar_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bar_menu.setObjectName("bar_menu")

        '''Проверить себя кнопка'''
        self.btn_checkup = QtWidgets.QPushButton(self.bar_menu)
        self.btn_checkup.setGeometry(QtCore.QRect(70, 140, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_checkup.setFont(font)
        self.btn_checkup.setStyleSheet("QPushButton{\n"
                                       "    background-color: #fb5;\n"
                                       "    border-radius: 25;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed{\n"
                                       "    color: #fb5;\n"
                                       "    border: 2px solid #fb5;\n"
                                       "    background-color: #22222e;\n"
                                       "}")
        self.btn_checkup.setObjectName("btn_checkup")

        '''Текущий список кнопка'''
        self.btn_show_corrent_list = QtWidgets.QPushButton(self.bar_menu)
        self.btn_show_corrent_list.setGeometry(QtCore.QRect(70, 80, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_show_corrent_list.setFont(font)
        self.btn_show_corrent_list.setStyleSheet("QPushButton{\n"
                                                 "    background-color: #fb5;\n"
                                                 "    border-radius: 25;\n"
                                                 "}\n"
                                                 "\n"
                                                 "QPushButton:pressed{\n"
                                                 "    color: #fb5;\n"
                                                 "    border: 2px solid #fb5;\n"
                                                 "    background-color: #22222e;\n"
                                                 "}")
        self.btn_show_corrent_list.setObjectName("btn_show_corrent_list")

        self.text_add_words = QtWidgets.QLineEdit(self.bar_menu)
        self.text_add_words.setGeometry(QtCore.QRect(70, 200, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_add_words.setFont(font)
        self.text_add_words.setStyleSheet("    background-color: #fb5;\n"
                                          "    border-radius: 25;")
        self.text_add_words.setAlignment(QtCore.Qt.AlignCenter)
        self.text_add_words.setObjectName("add_words_line")

        self.text_new_list = QtWidgets.QLineEdit(self.bar_menu)
        self.text_new_list.setGeometry(QtCore.QRect(70, 20, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_new_list.setFont(font)
        self.text_new_list.setStyleSheet("    background-color: #fb5;\n"
                                         "    border-radius: 25;")
        self.text_new_list.setAlignment(QtCore.Qt.AlignCenter)
        self.text_new_list.setObjectName("new_list_line")

        self.bar_list = QtWidgets.QFrame(self.centralwidget)
        self.bar_list.setGeometry(QtCore.QRect(0, 70, 341, 271))
        self.bar_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bar_list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bar_list.setObjectName("bar_list")

        self.list_corrent_and_add = QtWidgets.QListWidget(self.bar_list)
        self.list_corrent_and_add.setGeometry(QtCore.QRect(10, 10, 321, 251))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.list_corrent_and_add.setFont(font)
        self.list_corrent_and_add.setStyleSheet("background-color: white;\n"
                                                "\n"
                                                "")
        self.list_corrent_and_add.setAlternatingRowColors(True)
        self.list_corrent_and_add.setObjectName("listWidget")

        self.bar_chechup = QtWidgets.QFrame(self.centralwidget)
        self.bar_chechup.setGeometry(QtCore.QRect(0, 70, 335, 278))
        self.bar_chechup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bar_chechup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bar_chechup.setObjectName("bar_chechup")

        self.text_answer = QtWidgets.QLineEdit(self.bar_chechup)
        self.text_answer.setGeometry(QtCore.QRect(15, 50, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_answer.setFont(font)
        self.text_answer.setStyleSheet("background-color: white")
        self.text_answer.setObjectName("input_line")

        self.lbl_question = QtWidgets.QLabel(self.bar_chechup)
        self.lbl_question.setGeometry(QtCore.QRect(15, 10, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setPointSize(15)
        self.lbl_question.setFont(font)
        self.lbl_question.setStyleSheet("background-color: silver")
        self.lbl_question.setObjectName("lbl_question")

        self.list_chechup = QtWidgets.QListWidget(self.bar_chechup)
        self.list_chechup.setGeometry(QtCore.QRect(15, 90, 311, 181))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.list_chechup.setFont(font)
        self.list_chechup.setStyleSheet("background-color: white")
        self.list_chechup.setAlternatingRowColors(True)
        self.list_chechup.setObjectName("chechup_list")

        self.btn_answer = QtWidgets.QPushButton(self.bar_chechup)
        self.btn_answer.setGeometry(QtCore.QRect(215, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_answer.setFont(font)
        self.btn_answer.setStyleSheet("QPushButton{\n"
                                      "    background-color: #fb5;\n"
                                      "    border-radius: 10;\n"
                                      "    border: 2px solid  #22222e;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "    color: #fb5;\n"
                                      "    border: 2px solid #fb5;\n"
                                      "    background-color: #22222e;\n"
                                      "}")
        self.btn_answer.setObjectName("pushButton")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Memoreal"))
        self.lbl_status.setText(_translate("MainWindow",
                                           "<html><head/><body><p><span style=\" font-size:24pt;\">Меню</span></p></body></html>"))
        self.btn_back_to_menu.setText(_translate("MainWindow", "Назад"))
        self.btn_checkup.setText(_translate("MainWindow", "Проверить себя"))
        self.btn_show_corrent_list.setText(_translate("MainWindow", "Вывести список"))
        self.text_add_words.setPlaceholderText(_translate("MainWindow", "Добавить слова"))
        self.text_new_list.setPlaceholderText(_translate("MainWindow", "Новый список"))
        self.lbl_question.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_answer.setText(_translate("MainWindow", "Ответить"))
        self.text_answer.setPlaceholderText(_translate('MainWindow', 'Введите ваш ответ'))
        self.btn_answer.setShortcut(_translate('MainWindow', 'Return'))
